
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTUNjMkxaaWRVTkl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNE1qUXhNekV4TlRkYUZ3MHpOVEE0TWpJeE16RTJOVGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURtdDJEVFRqazhnZEtIL2tLV1IzalE1Q1JEaHJLT1lXSThiTTAwZzU3WlpIcXhobHlranhUdDNROFAKL0lveHRkczk4NzhxVGFNT2R4VVl3NzR1MStvOXBNTWdManFKbWN5VFRXejlESHJ0bGpvQjNnQkFXZForMUd6VApDcHo0RFA2TW1QSmw5TUo4c0xJR3Z0U2RVa0tBWWNBamRYVDRBVThlVmM2cXJRVisxOTBuZklOSnJQZXRXdXQyCkNXS0VCSEFaTUg5QzRpRDltMjRJUWhhcWl5bGQ2Vm1aNHhIUGNsYzNxZWlMNTJhSXIvaTdLSDB6UkNIZ3pTdjcKUzdmUTlHRDlFQ1lWSk1vYUM0ZkZQbXVvU1U5Zkl1V3RRaU1xNFMyV3VoOGg3QUxaTTBsZXNtTzhmc2lOdjM4cwpyOGVOYThFWW1OQVFMV0JyODRNbjE3SzJsNVkzQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRSVBXbUYyd1JlR3JaSW44Rmt4OCswMjRpSkZ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ2dndTBaR0wzagpFZGN6NHF4QXRZQ1MxK2VwZDA1Vjk0cFQ3ZlI5cXJLZkx3ZUZEUGJsM1R3cDVxK0VNRXl1V2xoQitNNUNxRWpMClphM1J4NkhSNkFwdFhQRHpBOXM1anpZaXdwNjh6WE9PNS82Uk1tWDF2WG1XdktGRjJzbDI4OVczZmhObldSWFoKc1NGSWVtNFJHZVZlTjFJL2xqNEhFSTJTcHlUS3FudGY3T05PTU4rZzd0dTc1bThWc1BYM1FUL0pyR25QMVlMWQpDZ2w1dFFUMjBPMmEyOFMwd2RQWTgwNkdqQUxYUjVMVDExbGVkYXNiUGJhNVRnNmRYYVZ1eGtnSGtOSEQxWVBxCkpRSUtlaWVvbTMranFRcmEyalBzdDkxTEpha2N1MHpLZUdBYzRicCsrKzRURmxNTDhpSzZrVjJMYlNoTDZUZWgKdmRWTWMrUForYWZpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://a670d040-a116-43fb-81f9-2b7ca14cb6d6.eu-central-3-gw.linodelke.net:443
  name: lke510348

users:
- name: lke510348-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5fOC1Eakt2OS1ydFNqQktoQUhRYktPUzRFX0ozZUx0U0FRSURMVERFZnMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4td3RraHAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMThhNmVlMjItYTM0NS00YmM4LWJhNDEtNjRjZTdlZWVjM2Y4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.VDoPsn7TmRPir6aXFZ1GJO7otAsBn0M6wQAOxz7OQiqjhW9NwIQnFkeKqzolFEb7ypFYeSyKggPnFwNrRYjMc15Xm7F7_Qvyeh_I44oDNCPoyguf8OUo4gWXPbWTgrn8al8VUsmdz24uegpboJZSKG-ayff3vev-HMjKV7MhHrulkv8iIQc1uQGi3sVkybSi-chbulM9TJ87YHpwrchz81FdtqY1rLMJZTXO0MDf4Ik6JNJoSkVkXKV5TirsI78oxAk2GIX8C1GSl9ppv4Q9RDI6xbO1DezZ5FHSWNLzMRFHdV_xUzmgFCMQTcPO8yjjpB3eOy2PptY6tcYmhlyvkA

contexts:
- context:
    cluster: lke510348
    namespace: default
    user: lke510348-admin
  name: lke510348-ctx

current-context: lke510348-ctx
